default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database:  mini-app-active_admin_development

test:
  <<: *default
  database:  mini-app-active_admin_test